### PR TITLE
get-pkg update

### PR DESCRIPTION
**Pull request by stefanwalther**
Update get-pkg to v1.0.0 + also update all other dependencies at the same time.

### CODE REVIEW

**Comment by doowb** [comment]
@stefanwalther will you also update the `.travis.yml` file since some of those new dependency versions don't work on older versions of node. For instance `data-store` requires node 8 now.

**Comment by jonschlinkert** [comment]
Does `engine` in package.json need to be updated too?

**Comment by doowb** [comment]
Yes, probably to `>=8`

**Comment by stefanwalther** [comment]
Sorry, will do, for this and all the other repos ... ran out of time earlier today ...

**Comment by stefanwalther** [comment]
OK; done, IMHO ready to be merged. Thx @jonschlinkert & @doowb .

**Comment by jonschlinkert** [comment]
thanks!

**Comment by stefanwalther** [comment]
Sorry, I on purpose (because I can't do the `npm publish`) didn't bump the version of `reflinks`, but I think it makes sense to bump it to not get confused with all the related PR.
Can you pls do that, or should I do another PR?

See https://github.com/verbose/verb-generate-readme/issues/23

**Pull request merged**
