### PR TITLE
Cleanup unused

### PR DESCRIPTION
**Pull request by tunnckoCore**
and move `utils` to root.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks this is great. I completely forgot to do that after creating pkg-cache

**Comment by jonschlinkert** [comment]
Released and published as 0.2.5. thanks again!

**Comment by tunnckoCore** [comment]
Great! Yea, I noticed that it seems you started `pkg-store/cache` from here :D

**Comment by jonschlinkert** [comment]
> I noticed that it seems you started pkg-store/cache from here :D

lol yeah, I had the idea and wanted to get it working here first. then forgot to remove it. Seems like pkg-cache will come in useful

**Pull request merged**
